### ISSUE TITLE
Display unit not taken into account when displaying attribute set values

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/hdbpp-viewer#1]
Hi,

HDB++ Viewer does not seem to take into account the display unit when displaying attribute set values (in chart and table).
You can see this easily at the ESRF by displaying the master source frequency attribute which is defined with a display unit conversion factor of 1.0E-6. The read value is displayed in MHz whereas the write value is displayed in Hz.

Cheers,
Reynald

**Comment by JeanLucPons** [comment]
The calculation of the conversion is done by the extraction API.
Fixed in HDB++ 1.14.
