### ISSUE TITLE
Display milliseconds/microseconds in image viewer and profile windows

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/hdbpp-viewer#2]
Hi,

It would be useful to display the time with a millisecond or microsecond (option) precision for the data displayed in the image tab of the HDB++ Viewer. 
This precision would be useful as well in the vertical profile and horizontal profile windows.

Thanks in advance.

**Comment by JeanLucPons** [comment]
Fixed in ATK 4.1.41.
